<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MvcBankAccountSim.Infrastructure\MvcBankAccountSim.Infrastructure.csproj" />
    <ProjectReference Include="..\MvcBankAccountSim.Application\MvcBankAccountSim.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
