// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511174849_UpdateProductConfiguration")]
    partial class UpdateProductConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Smartphones",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tablets",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laptops",
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "johnretail.admin@retail.com",
                            FirstName = "John",
                            LastName = "Retail",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Product_StockQuantity_NonNegative", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "{\"OS\":\"iOS 26\",\"CPU\":\"A19\",\"GPU\":\"Apple GPU 5 Cores\",\"RAM\":\"8 GB\",\"Memory\":\"256 GB\",\"Cameras\":\"Main: 48.0 MP + 48.0 MP, Front: 18.0 MP\",\"Screen\":\"6.3 inch OLED, 120Hz, Super Retina XDR (1206 x 2622 Pixels), MAX 3000 nits\",\"Battery Duration\":\"30h\",\"SIM Profile\":\"1 eSIM, 1 nano SIM\"}",
                            ImageUrl = "iphone-17-2-400x400.jpg",
                            Name = "iPhone 17 256GB",
                            Price = 913.52m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "{\"OS\":\"Windows 11\",\"CPU\":\"Intel Core i7 Raptor Lake - 14700HX, 20 Cores 28 Threads, 2.10GHz\",\"GPU\":\"NVIDIA GeForce RTX 5050, 8 GB, 115W\",\"RAM\":\"16 GB DDR5 5600MHz, MAX 32 GB\",\"Hard Drive\":\"1 TB SSD M.2 NVMe PCIe Gen 4 x 4 2242, Support 1 slot for SSD M.2 PCIe (MAX 1TB 2280)\", \"Screen\":\"15.1 inch OLED 165Hz, 100% DCI-P3\"}",
                            ImageUrl = "lenovo-gaming-legion-5-15irx10-i7-14700hx-83ly00hyvn-1-638909844112150811-750x500.jpg",
                            Name = "Laptop Lenovo Gaming Legion 5 15IRX10 - 83LY00HYVN (i7 14700HX, 16GB, 1TB, RTX 5050 8GB, WQXGA 165Hz, OfficeH24, Win11)",
                            Price = 1636.79m,
                            StockQuantity = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
